### ISSUE TITLE
Uncaught TypeError: Cannot read property 'results' of null

### ISSUE THREAD

**Issue by jpwesselink** [catacgc/markdown-helpers#1]
Uncaught TypeError: Cannot read property 'results' of null

**Atom Version**: 0.153.0
**System**: Mac OS X 10.10.1
**Thrown From**: [markdown-helpers](https://github.com/catacgc/markdown-helpers) package, v0.2.1
### Steps To Reproduce
1. select text 'gulp'.
2. Toggle command palette.
3. Type 'link'.
4. Use keyboard to scroll to 'Markdown Helpers: Convert Link'.
5. Press enter.
### Stack Trace

```
At /Users/jp/.atom/packages/markdown-helpers/lib/markdown-helpers.coffee:38

TypeError: Cannot read property 'results' of null
  at GoogleWebConvertor.handleResponse (/Users/jp/.atom/packages/markdown-helpers/lib/markdown-helpers.coffee:38:31)
  at Request._callback (/Users/jp/.atom/packages/markdown-helpers/lib/markdown-helpers.coffee:33:14)
  at Request.self.callback (/Users/jp/.atom/packages/markdown-helpers/node_modules/request/request.js:121:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Users/jp/.atom/packages/markdown-helpers/node_modules/request/request.js:985:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Users/jp/.atom/packages/markdown-helpers/node_modules/request/request.js:936:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:378:11)

```

/cc @atom/core

**Comment by catacgc** [comment]
Fixed in v0.3.0
