### ISSUE TITLE
Uncaught TypeError: Cannot read property 'results' of undefined

### ISSUE THREAD

**Issue by 7k50** [catacgc/markdown-helpers#15]
[Enter steps to reproduce below:]

Used <kbd>ctrl + l</kbd> on several text snippets in a row, suddenly got error for one that refuses to convert. May be that there is a <kbd>-</kbd> in the text.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [markdown-helpers](https://github.com/catacgc/markdown-helpers) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'results' of undefined

```
At /Users/me/.atom/packages/markdown-helpers/lib/main.coffee:40

TypeError: Cannot read property 'results' of undefined
    at GoogleWebConvertor.handleResponse (/Users/me/.atom/packages/markdown-helpers/lib/main.coffee:40:39)
    at Request._callback (/Users/me/.atom/packages/markdown-helpers/lib/main.coffee:35:14)
    at Request.self.callback (/Users/me/.atom/packages/markdown-helpers/node_modules/request/request.js:121:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/me/.atom/packages/markdown-helpers/node_modules/request/request.js:985:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/me/.atom/packages/markdown-helpers/node_modules/request/request.js:936:12)
    at emitNone (events.js:72:20)
```
### Commands

```
     -1:01.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:00.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:00.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:59.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:55.2.0 markdown-helpers:convert-link (atom-text-editor.editor.is-focused)
     -0:48.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:36.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:36 core:move-right (atom-text-editor.editor.is-focused)
     -0:35.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:34.9.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:33.4.0 markdown-helpers:convert-link (atom-text-editor.editor.is-focused)
     -0:31.8.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:26.5.0 markdown-helpers:convert-link (atom-text-editor.editor.is-focused)
     -0:20.2.0 core:undo (atom-text-editor.editor.is-focused)
  4x -0:16.7.0 markdown-helpers:convert-link (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "spell-check",
      "metrics",
      "autosave",
      "autocomplete-snippets",
      "autocomplete-plus",
      "minimap",
      "color-picker"
    ],
    "openEmptyEditorOnStart": false,
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
emmet, v2.3.16
emmet-snippets-compatibility, v1.0.1
ever-notedown, v0.2.16
markdown-helpers, v0.3.0
markdown-mindmap, v0.2.4
markdown-writer, v2.0.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by asanakoy** [comment]
Also have the same issue. I guess this repo is not maintained anymore?
